from pathlib import Path

import pandas as pd
import pytest

from bankstress.tail_validation import (
    _historical_grid, _prepare_jump_off_state, _rearrange, _recursive_path,
    assert_not_cumulative_q90, prediction_target_dictionary,
    predict_quantile, quarter_sequence, validate_target_dictionary,
)
from bankstress.artifacts import code_identity


def test_prediction_targets_and_nominal_labels_are_distinct():
    rows = prediction_target_dictionary()
    validate_target_dictionary(rows)
    indexed = {row["target_id"]: row for row in rows}
    assert indexed["one_step_q90_upper_quantile"]["nominal_exceedance_rate"] == 0.10
    assert indexed["one_step_q50_q90_band"]["nominal_coverage"] == 0.40
    assert indexed["residual_calibrated_two_sided_90_interval"]["status"] == "NOT_EVALUATED"
    assert indexed["multi_period_cumulative_loss_q90"]["status"] == "NOT_EVALUATED"


def test_quantile_crossing_is_counted_and_raw_predictions_are_preserved():
    base = pd.DataFrame({"bank_id": ["1"], "segment": ["CRE"], "forecast_origin": [pd.Timestamp("2020-02-15")],
                         "target_period": [pd.Timestamp("2020-03-31")], "nco_rate": [0.2]})
    frames = {}
    for tau, value in [(0.5, 0.3), (0.75, 0.2), (0.9, 0.4)]:
        frames[tau] = base.assign(prediction_raw=value)
    repaired, count = _rearrange(frames)
    assert count == 1
    assert repaired[0.5].prediction_raw.iloc[0] == 0.3
    assert [repaired[t].prediction_rearranged.iloc[0] for t in sorted(repaired)] == [0.2, 0.3, 0.4]


def test_actual_exceedance_count_is_not_a_coverage_proxy():
    actual = pd.Series([0.0, 2.0, 3.0])
    prediction = pd.Series([1.0, 1.0, 4.0])
    assert int((actual > prediction).sum()) == 1
    assert float((actual > prediction).mean()) == pytest.approx(1 / 3)


def test_quarter_block_boundaries_are_complete():
    quarters = quarter_sequence(pd.Timestamp("2007-01-01"), pd.Timestamp("2010-12-31"))
    assert len(quarters) == 16
    assert quarters[0] == pd.Timestamp("2007-03-31")
    assert quarters[-1] == pd.Timestamp("2010-12-31")


def test_fixed_q90_feedback_cannot_be_labelled_cumulative_q90():
    assert_not_cumulative_q90("recursive_quantile_sensitivity_not_distribution")
    with pytest.raises(ValueError, match="sensitivity"):
        assert_not_cumulative_q90("multi_period_cumulative_loss_q90")


def test_generated_artifacts_preserve_paths_when_realized_values_are_missing():
    path = Path(__file__).resolve().parents[1] / "outputs/repair/r3/validation_summary.json"
    if not path.exists():
        pytest.skip("R3 artifact is generated by scripts/validate_models.py")
    summary = pd.read_json(path, typ="series")
    assert summary["continuous_path_row_count"] == summary["expected_continuous_path_row_count"]
    assert summary["paths_preserved_with_missing_actual"] > 0
    assert summary["future_control_leakage_count"] == 0
    paths = pd.read_parquet(path.parents[2] / "validation/pseudo_stress.parquet")
    window_end = {"GFC": "2006-12-31", "COVID": "2019-12-31", "High_Rate_CRE": "2021-12-31"}
    ends = paths.pseudo_window.map(window_end).map(pd.Timestamp)
    assert paths.bank_controls_source_period.le(ends).all()
    assert paths.lagged_loan_growth_source_period.eq(ends).all()
    assert paths.lagged_loan_growth_prior_component_source_period.eq(ends - pd.offsets.QuarterEnd()).all()


def test_reported_exceedance_count_matches_saved_actual_predictions():
    root = Path(__file__).resolve().parents[1]
    predictions_path = root / "outputs/validation/oos_predictions.parquet"
    if not predictions_path.exists():
        pytest.skip("R3 artifact is generated by scripts/validate_models.py")
    predictions = pd.read_parquet(predictions_path)
    metrics = pd.read_csv(root / "outputs/validation/tail_metrics.csv")
    selected = predictions[(predictions.window.eq(1)) & (predictions.segment.eq("CRE")) &
                           (predictions.model_family.eq("dynamic_quantile")) & (predictions.tau.eq(0.9)) &
                           (predictions.prediction_version.eq("POST_REARRANGEMENT"))].dropna(subset=["nco_rate"])
    reported = metrics[(metrics.window.astype(str).eq("1")) & (metrics.segment.eq("CRE")) &
                       (metrics.model_family.eq("dynamic_quantile")) & (metrics.tau.eq(0.9)) &
                       (metrics.prediction_version.eq("POST_REARRANGEMENT"))].iloc[0]
    assert reported.exceedance_count == int((selected.nco_rate > selected.prediction).sum())


def test_predict_quantile_does_not_require_realized_target():
    class Result:
        def predict(self, values):
            return [0.1] * len(values)
    from bankstress.tail_validation import QuantileFit
    fit = QuantileFit(Result(), ["lagged_nco_rate"], ["1", "2"], "1", 0.9, 1, True, None)
    data = pd.DataFrame({"bank_id": ["1"], "segment": ["CRE"], "lagged_nco_rate": [0.2], "nco_rate": [float("nan")]})
    assert len(predict_quantile(fit, data)) == 1


def test_jump_off_uses_current_controls_when_lagged_values_deliberately_differ(monkeypatch):
    train_end = pd.Timestamp("2019-12-31")
    train = pd.DataFrame({
        "bank_id": ["1"], "segment": ["CRE"], "target_period": [train_end],
        "report_period": [pd.Timestamp("2019-09-30")], "nco_rate": [0.11],
        "npl_rate": [0.22], "allowance_coverage_r2": [1.33], "tier1_ratio": [0.144],
        "total_loans": [120.0], "origin_total_loans": [100.0],
        "lagged_nco_rate": [9.11], "forecast_origin": [pd.Timestamp("2019-11-14")],
        "lagged_noncurrent_ratio": [9.22], "lagged_allowance_coverage": [9.33],
        "lagged_tier1_ratio": [9.44], "lagged_loan_growth": [9.55],
        "origin_exposure": [80.0],
    })
    jump, excluded = _prepare_jump_off_state(train, train_end)
    assert excluded == 0
    assert jump.iloc[0]["lagged_noncurrent_ratio"] == pytest.approx(0.22)
    assert jump.iloc[0]["lagged_allowance_coverage"] == pytest.approx(1.33)
    assert jump.iloc[0]["lagged_tier1_ratio"] == pytest.approx(0.144)
    assert jump.iloc[0]["lagged_loan_growth"] == pytest.approx(0.20)
    predictors = ["lagged_nco_rate", "lagged_noncurrent_ratio", "lagged_allowance_coverage",
                  "lagged_loan_growth", "lagged_tier1_ratio"]
    grid = _historical_grid(train, "CRE", {"test_start": "2020-01-01", "test_end": "2020-06-30"}, jump, predictors)
    for term in predictors[1:]:
        assert grid[term].nunique() == 1
        assert grid[f"{term}_source_period"].eq(train_end).all()
    assert grid["lagged_loan_growth_prior_component_source_period"].eq(pd.Timestamp("2019-09-30")).all()
    monkeypatch.setattr(
        "bankstress.tail_validation._predict_entity_fe",
        lambda fit, current, outcome: current.assign(prediction=current.lagged_nco_rate),
    )
    path = _recursive_path({}, "mean", grid, jump, "conditional_mean_recursive_path")
    assert path.iloc[0].prediction == pytest.approx(0.11)
    assert path.iloc[0].lagged_nco_rate_source_period == train_end
    assert path.iloc[0].lagged_nco_rate_source_type == "ACTUAL_JUMP_OFF"


def test_recursive_nco_lineage_carries_last_modeled_state_across_unavailable_middle_quarter(monkeypatch):
    train_end = pd.Timestamp("2019-12-31")
    jump = pd.DataFrame({
        "bank_id": ["1"], "target_period": [train_end], "nco_rate": [0.11],
    })
    dates = pd.to_datetime(["2020-03-31", "2020-06-30", "2020-09-30"])
    grid = pd.DataFrame({"bank_id": ["1"] * 3, "target_period": dates})

    def predict_with_middle_gap(fit, current, outcome):
        if current.target_period.iloc[0] == pd.Timestamp("2020-06-30"):
            return current.iloc[0:0].assign(prediction=pd.Series(dtype=float))
        return current.assign(prediction=current.lagged_nco_rate + 0.09)

    monkeypatch.setattr("bankstress.tail_validation._predict_entity_fe", predict_with_middle_gap)
    path = _recursive_path({}, "mean", grid, jump, "conditional_mean_recursive_path")

    first, middle, following = (path[path.target_period.eq(date)].iloc[0] for date in dates)
    assert first.lagged_nco_rate == pytest.approx(0.11)
    assert first.lagged_nco_rate_source_period == train_end
    assert first.lagged_nco_rate_source_type == "ACTUAL_JUMP_OFF"
    assert middle.lagged_nco_rate == pytest.approx(0.20)
    assert middle.lagged_nco_rate_source_period == pd.Timestamp("2020-03-31")
    assert middle.lagged_nco_rate_source_type == "MODELED_RECURSIVE"
    assert not middle.prediction_available
    assert following.lagged_nco_rate == pytest.approx(0.20)
    assert following.lagged_nco_rate_source_period == pd.Timestamp("2020-03-31")
    assert following.lagged_nco_rate_source_type == "MODELED_RECURSIVE"


def test_artifact_lineage_fails_closed_for_untracked_source_file(tmp_path):
    import subprocess

    subprocess.run(["git", "init"], cwd=tmp_path, check=True, capture_output=True)
    subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=tmp_path, check=True)
    subprocess.run(["git", "config", "user.name", "Test"], cwd=tmp_path, check=True)
    (tmp_path / "src").mkdir()
    (tmp_path / "scripts").mkdir()
    (tmp_path / "src/tracked.py").write_text("VALUE = 1\n", encoding="utf-8")
    (tmp_path / "scripts/tracked.py").write_text("VALUE = 1\n", encoding="utf-8")
    subprocess.run(["git", "add", "src", "scripts"], cwd=tmp_path, check=True)
    subprocess.run(["git", "commit", "-m", "checkpoint"], cwd=tmp_path, check=True, capture_output=True)
    (tmp_path / "src/untracked.py").write_text("VALUE = 2\n", encoding="utf-8")
    with pytest.raises(ValueError, match="untracked source files.*src/untracked.py"):
        code_identity(tmp_path)
